name: Build and Release CAPE Docker Project

on:
  push:
    tags:
      - 'v*'  # This assumes that you use semantic versioning

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Ensures submodules are fetched

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.16'  # Specify your Go version

    - name: Build project docker container
      run: make all

    - name: Set up Docker Environment
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag cape:kvm celyrin/cape:kvm
        docker tag cape:kvm celyrin/cape:${{ github.sha }}
        docker push celyrin/cape:kvm
        docker push celyrin/cape:${{ github.sha }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |  # Updated release description here
          For this version's release, we use KVM for virtualization.
          Docker images are available on Docker Hub: `celyrin/cape:kvm` and `celyrin/cape:${{ github.sha }}`
        draft: false
        prerelease: false

