name: Build and Release CAPE Docker Project

on:
  push:
    branches:
      - main  # Or your default branch
    tags:
      - 'v*'  # This assumes that you use semantic versioning

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Ensures submodules are fetched

    - name: Set up Docker Environment
      uses: docker/setup-buildx-action@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.16'  # Specify your Go version

    - name: Build project binaries
      run: make all

    - name: Save Docker image
      run: docker save cape:latest | gzip > cape-docker.tar.gz

    - name: Package Binaries
      run: tar -czvf bin.tar.gz bin

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |  # Updated release description here
          This release contains the following files:
          - `cape-docker.tar.gz`: Docker image of the latest build. Use `gunzip -c cape-docker.tar.gz | docker load` to load this image into your Docker environment.
          - `bin.tar.gz`: Archive of the binaries.
        draft: false
        prerelease: false

    - name: Upload Docker Image to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cape-docker.tar.gz
        asset_name: cape-docker.tar.gz
        asset_content_type: application/octet-stream

    - name: Upload Binaries Archive to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin.tar.gz
        asset_name: bin.tar.gz
        asset_content_type: application/gzip
